name: Compile ESP32-C3 Firmware

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Platform
        run: |
          arduino-cli core update-index --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

      - name: Compile Sketch to BIN
        run: |
          # --export-binaries ထည့်ပေးထားလို့ Flash ဖိုင်အပြည့်စုံစုံလင်လင် ထွက်လာမှာဖြစ်ပါတယ်
          arduino-cli compile --fqbn esp32:esp32:esp32c3 --export-binaries --output-dir ./build ./wifi_ap_test/wifi_ap_test.ino

      - name: Upload Binary Artifacts
        uses: actions/upload-artifact@v4 # <- ဒီနေရာကို v4 ပြောင်းလိုက်လို့ error ရှင်းသွားပါလိမ့်မယ်
        with:
          name: esp32c3-binaries
          path: ./build/
